title: Automation
icon: mdi:auto-fix
path: automation
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: Automations
      show_header_toggle: false
    filter:
      include: 
        - domain: automation
